version: '3.8'
services:
  web:
    env_file:
      - ~/Projects/.environment/front-end/.env
    build:
      context: .
      target: 'build-stage'
    ports:
      - '80:80'
    networks:
      - biweekly_network
    # restart: always
    image: biweekly-front-end:latest
    volumes:
      - ".:/app"

networks:
  biweekly_network:
    external: true
