# for local development
# no se esta utilizando por ahora
version: '3.8'
services:
  quasar:
    build:
      context: .
      target: 'develop-stage'
    ports:
      - '8080:8080'
    volumes:
      - '.:/app'
    command: /bin/sh -c "yarn && quasar dev"
    networks:
      - biweekly_network

networks:
  biweekly_network:
    external: true
