version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    networks:
      - quasar-network
    # - biweekly_network
    restart: always
    image: biweekly-front-end:latest

networks:
  quasar-network:
    driver: bridge
