version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ~/Projects/.environment/front-end/.env
    container_name: biweekly-app
    ports:
      - '8080:80'
    networks:
      - biweekly_network

  nginx:
    image: nginx:alpine
    env_file:
      - ~/Projects/.environment/front-end/.env
    container_name: nginx-app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - biweekly_network
    depends_on:
      - app

networks:
  biweekly_network:
    external: true
